# Generated by Django 5.0.14 on 2026-02-12 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0002_initial'),
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productinquiry',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productinquiry',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='market.productlisting'),
        ),
    ]
