# Generated by Django 5.0.14 on 2026-02-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('subsidy', 'Subsidy'), ('loan', 'Loan'), ('insurance', 'Insurance'), ('training', 'Training'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('level', models.CharField(choices=[('central', 'Central Government'), ('state', 'State Government'), ('district', 'District Level')], max_length=20)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('benefits', models.TextField()),
                ('documents_required', models.TextField()),
                ('application_process', models.TextField()),
                ('states', models.JSONField(default=list, help_text='List of applicable states')),
                ('official_website', models.URLField(blank=True)),
                ('application_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government Scheme',
                'verbose_name_plural': 'Government Schemes',
                'ordering': ['-created_at'],
            },
        ),
    ]
