# Generated by Django 5.0.14 on 2026-02-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid'), ('all', 'All Season')], max_length=10)),
                ('duration_days', models.IntegerField(help_text='Crop duration in days')),
                ('suitable_soil_types', models.JSONField(default=list)),
                ('ph_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ph_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nitrogen_requirement', models.IntegerField(help_text='N requirement (kg/acre)')),
                ('phosphorus_requirement', models.IntegerField(help_text='P requirement (kg/acre)')),
                ('potassium_requirement', models.IntegerField(help_text='K requirement (kg/acre)')),
                ('temp_min', models.DecimalField(decimal_places=2, help_text='Minimum temperature (°C)', max_digits=5)),
                ('temp_max', models.DecimalField(decimal_places=2, help_text='Maximum temperature (°C)', max_digits=5)),
                ('rainfall_min', models.IntegerField(help_text='Minimum rainfall (mm)')),
                ('rainfall_max', models.IntegerField(help_text='Maximum rainfall (mm)')),
                ('water_requirement', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.IntegerField()),
                ('phosphorus', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=7)),
                ('state', models.CharField(max_length=100)),
                ('recommended_crops', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
