# Generated by Django 5.0.14 on 2026-02-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprecommendation',
            name='humidity',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='ph',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='rainfall',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='temperature',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
