# Generated by Django 5.0.14 on 2026-02-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_alter_croprecommendation_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprecommendation',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
